# Generated by Django 4.1.4 on 2023-04-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_question_can_choose_many_question_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
